name = "elbespararen"
compatibility_date = "2025-03-25"
compatibility_flags = ["nodejs_compat"]

pages_build_output_dir = ".vercel/output/static"

[env.production]
r2_buckets = [
  { binding = "BILL_IMAGES", bucket_name = "elbespararen-bill-images", preview_bucket_name = "elbespararen-bill-images" }
]
d1_databases = [
  { binding = "DB", database_name = "elbespararen-db", database_id = "a475e6e6-5228-4598-8751-634e7de05ec0" }
]

[env.preview]
r2_buckets = [
  { binding = "BILL_IMAGES", bucket_name = "elbespararen-bill-images", preview_bucket_name = "elbespararen-bill-images" }
]
d1_databases = [
  { binding = "DB", database_name = "elbespararen-db", database_id = "a475e6e6-5228-4598-8751-634e7de05ec0" }
]