name = "elbespararen"
compatibility_date = "2024-01-01"
pages_build_output_dir = ".next"

[[d1_databases]]
binding = "DB"
database_name = "elbespararen-db"
database_id = "your-database-id-here"

[env.production]
name = "elbespararen-prod"

[[env.production.d1_databases]]
binding = "DB"
database_name = "elbespararen-db"
database_id = "your-database-id-here"