# Cloudflare Wrangler konfiguration för Elbespararen v7
# https://developers.cloudflare.com/workers/wrangler/configuration/

name = "elbespararen"
main = "src/index.js"
compatibility_date = "2024-01-15"
compatibility_flags = ["nodejs_compat"]

# Next.js på Cloudflare Pages
[env.production]
name = "elbespararen-prod"

[env.staging]
name = "elbespararen-staging"

# D1 Database konfiguration
[[d1_databases]]
binding = "DB"
database_name = "elbespararen-db"
database_id = "your-database-id-here" # Ersätt med riktigt ID från Cloudflare Dashboard
migrations_dir = "src/lib/database/migrations"

# Environment variables
[vars]
NODE_ENV = "production"
NEXT_PUBLIC_APP_URL = "https://elbespararen.pages.dev"

# Secrets (sätts via wrangler secret put)
# OPENAI_API_KEY = "your-openai-api-key"
# TELEGRAM_BOT_TOKEN = "your-telegram-bot-token"
# TELEGRAM_CHAT_ID = "your-telegram-chat-id"

# Build konfiguration
[build]
command = "npm run build"
cwd = "."

# Pages konfiguration
[pages]
build_output_dir = ".next"
