name = "elbespararen"
compatibility_date = "2024-01-01"
pages_build_output_dir = ".vercel/output/static"

[[d1_databases]]
binding = "DB"
database_name = "elbespararen-db"
database_id = "a475e6e6-5228-4598-8751-634e7de05ec0"