# Cloudflare Workers konfiguration för Elbespararen v7
# OpenNext Cloudflare adapter configuration
# https://opennext.js.org/cloudflare

name = "elbespararen"
main = ".open-next/worker.js"
compatibility_date = "2025-03-25"
compatibility_flags = ["nodejs_compat"]

# Assets binding för statiska filer
[site]
bucket = ".open-next/assets"

# D1 Database konfiguration
[[d1_databases]]
binding = "DB"
database_name = "elbespararen-db"
database_id = "your-database-id-here" # Ersätt med riktigt ID från Cloudflare Dashboard
migrations_dir = "src/lib/database/migrations"

# Environment variables
[vars]
NODE_ENV = "production"

# Secrets (sätts via wrangler secret put)
# OPENAI_API_KEY = "your-openai-api-key"
# TELEGRAM_BOT_TOKEN = "your-telegram-bot-token"
# TELEGRAM_CHAT_ID = "your-telegram-chat-id"
