# Cloudflare Pages konfiguration för Elbespararen v7
# Next.js med @cloudflare/next-on-pages

name = "elbespararen"
compatibility_date = "2025-03-25"
pages_build_output_dir = ".vercel/output/static"

# Environment variables
[vars]
NODE_ENV = "production"

# D1 Database konfiguration (uncomment när du vill använda databas)
# [[d1_databases]]
# binding = "DB"
# database_name = "elbespararen-db"
# database_id = "your-database-id-here" # Kör 'wrangler d1 create elbespararen-db' för att få ID
# migrations_dir = "src/lib/database/migrations"

# Secrets (sätts via wrangler secret put)
# OPENAI_API_KEY = "your-openai-api-key"
# TELEGRAM_BOT_TOKEN = "your-telegram-bot-token"
# TELEGRAM_CHAT_ID = "your-telegram-chat-id"
