# Cloudflare Pages konfiguration för Elbespararen v7
# Next.js med @cloudflare/next-on-pages

name = "elbespararen"
compatibility_date = "2025-03-25"
pages_build_output_dir = ".vercel/output/static"

# Node.js compatibility för att hantera node:stream och andra Node.js moduler
compatibility_flags = ["nodejs_compat"]

# Environment variables
[vars]
NODE_ENV = "production"

# D1 Database konfiguration
[[d1_databases]]
binding = "DB"
database_name = "elbespararen-db"
database_id = "a475e6e6-5228-4598-8751-634e7de05ec0" # Ersätt vid behov om ID:t ändras
migrations_dir = "src/lib/database/migrations"

# Secrets (sätts via wrangler secret put)
# OPENAI_API_KEY = "your-openai-api-key"
# TELEGRAM_BOT_TOKEN = "your-telegram-bot-token"
# TELEGRAM_CHAT_ID = "your-telegram-chat-id"
